name: jb_music
description: Premium AI-powered Personal Music Platform with Embedded Audio Safeguards
version: 3.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Audio
  just_audio: ^0.9.46
  on_audio_query: ^2.9.0
  audio_service: ^0.18.0

  # UI
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Permissions & device
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.5

  # Utils
  path_provider: ^2.1.5
  path: ^1.9.1
  crypto: ^3.0.7

  # DI
  get_it: ^7.7.0

  # Voice
  vosk_flutter: ^0.3.48
  speech_to_text: ^7.4.0
  palette_generator: ^0.3.3+3  
  # --- Uncomment when you implement these features ---
    
  # audio_video_progress_bar: ^2.0.3  # custom progress bar

dependency_overrides:
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_tracks/demo_song.mp3
    - assets/mock_tracks/demo_song.lrc